language: c++

matrix:
  include:
    - os: linux
      env: CXX=clang-3.4
      addons: &clang34
        apt:
          packages:
            - clang-3.4
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.4

    - os: linux
      env: CXX=clang-3.5
      addons: &clang35
        apt:
          packages:
            - clang-3.5
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - os: linux
      env: CXX=clang-3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      env: CXX=clang-3.7
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise

    - os: linux
      env: CXX=gcc-4.9
      addons: &gcc49
        apt:
          packages:
            - g++-4.9
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: CXX=gcc-5
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: osx
      env: CXX=clang

before_script: ./build-v8.sh
script: CXXFLAGS="-isystem./v8/include -isystem./v8 "$CXXFLAGS LIBRARY_PATH="./v8/lib" make
after_success: LD_LIBRARY_PATH=.:./v8/lib ./v8pp_test -v --run-tests test/console.js test/file.js
