language: cpp
compiler:
  - clang
  - gcc

before_script:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - fetch --no-history v8
  - cd v8
  - gclient sync
  - make native library=shared -j8
  - sudo cp -r  -v include/* /usr/include
  - sudo install -v --mode=0644 out/native/lib.target/libv8.so /usr/lib/libv8.so
  - cd ..

script: make
after_success: LD_LIBRARY_PATH=. ./v8pp_test -v test/console.js test/file.js
