language: cpp
compiler: gcc

before_script: build-v8.sh
script: CXXFLAGS="-isystem./v8/include -isystem./v8" LIBRARY_PATH="./v8/lib" make
after_success: LD_LIBRARY_PATH=.:./v8/lib ./v8pp_test -v test/console.js test/file.js
